### ISSUE TITLE
Add semver 2 support to ctl version plugin

### ISSUE THREAD

**Issue by vegu** [20c/ctl#20]
https://semver.org/spec/v2.0.0.html

Add a `--pre-release` option that allows us to tag pre releases

`ctl version bump dev --pre-release beta`  would do `1.0.0-beta.1`
`ctl version bump patch --pre-release beta`  would do `1.0.1-beta`
`ctl version bump minor --pre-release beta`  would do `1.1.0-beta`
`ctl version bump major --pre-release beta` would do `2.0.0-beta`

Also switch to using https://pypi.org/project/semver/ for the version parsing and updating

**Comment by egfrank** [comment]
Hi @vegu I wanted to check in about the "dev" option.

With the current spec in the issue, it seems like i'd have to implement the function version_tuple to basically pull off the last number of the prerelease to signify the dev version.

i.e. `1.0.0-beta.1` would then be translated as a version_tuple  as ("1", "0", "0", "1") if we want to later be able to bump it up to `1.0.0-beta.2`

That seems simple enough but feels odd to me that we're including data from the prerelease identifier (i.e. "beta.1") in the `version_tuple`

Additionally, if the version is `1.0.0-beta.1`, would the following two commands produce a different result or the same result?
`ctl version bump dev`
`ctl version bump dev --prerelease beta`

Currently the way it's implemented, the first option would result in the `1.0.0.2`  and the second would result in `1.0.0-beta.2`

**Comment by egfrank** [comment]
Hi @vegu  so far I've replaced all the existing semver logic with the `semver` package, and added the prerelease as both a flag and an acceptable `bump` option.

Some questions:

What do we want to do with this section and the `no_auto_dev` tag? https://github.com/20c/ctl/blob/gh_20/src/ctl/plugins/version.py#L340

Right now we only give the option to add a prerelease flag when the user is doing some other bump ("major" "minor" or "path"). Is that right? 

What are any other commands we need? There is a "release" flag right now, how does that intersect with the prerelease option?

**Comment by egfrank** [comment]
Updating this issue with all the latest requirements for the feature:

1) `semver2` is the name of the new plugin
2) should use the `semver` package for bumping versions
3) `bump major` `bump minor` `bump patch` all act predictably
4) `bump prerelease` takes the last integer in the pre-release identifier and bumps it
- There is a `bump_prerelease` method already in `semver` so see if this is adequate, if not add logic around it
5) add a `--no-tag` that stops it from tagging in git
