### ISSUE TITLE
move default cachedir

### ISSUE THREAD

**Issue by grizz** [20c/ctl#29]
Should be `~/.cache/ctl/`

For example, for repos, should be `~/.cache/ctl/repo/github.com/$URL`

**Comment by egfrank** [comment]
Currently for the django template it's 

`~/.ctl/cache/github.com/20c/ctl-tmpl-django`

so obviously we'll switch `cache` and `ctl`. Do you want me to add the `repo` before `github.com` ? are there other options than `repo`?

**Comment by egfrank** [comment]
WIP here : https://github.com/20c/ctl/pull/30

**Comment by vegu** [comment]
i think the `repo` part should be added by the `repository` plugin

**Comment by egfrank** [comment]
Hi @vegu here's the updated PR with `repo` added and the `pyproject` change
